title='Example map'

[sim]
    epoch=2
    user_code='./lib.a_star.cpp.so'

[obstacle]
    x=[1,5,1]
    y=[1,2,3]

[size]
    x=10
    y=10

[robot]
    num_sensor=3
    x=0
    y=0
    target_x=5
    target_y=5